filter_settings.niklan_markdown:
  type: filter
  label: 'Markdown filter'

field.formatter.settings.niklan_responsive_media_thumbnail:
  type: mapping
  label: Responsive media thumbnail
  mapping:
    responsive_image_style:
      type: string
      label: 'Responsive image style'
    image_link:
      type: string
      label: 'Link image to'
    image_loading:
      type: mapping
      label: 'Image loading settings'
      mapping:
        attribute:
          type: string
          label: 'Loading attribute'