filter_settings.niklan_markdown:
  type: filter
  label: 'Markdown filter'

field.formatter.settings.niklan_media_remote_video_optimized:
  type: mapping
  label: 'Optimized remote video formatter'
  mapping:
    responsive_image_style:
      type: string
      label: 'The responsive image style ID'
