<?php

declare(strict_types=1);

namespace Drupal\niklan\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

final class TestForm extends ConfigFormBase {

  public function getFormId() {
    return 'niklan_test_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['test'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Test'),
      '#config_target' => 'niklan.about_settings:title',
    ];

    // TODO: Change the autogenerated stub.
    return parent::buildForm($form, $form_state);
  }

  protected function getEditableConfigNames() {
    return ['niklan.about_settings'];
  }

}
