<?php

declare(strict_types=1);

use Drupal\laszlo\Hook\Theme\NodePreprocess;
use Drupal\laszlo\Hook\Theme\PagePreprocess;

/**
 * Implements hook_preprocess_HOOK().
 */
function laszlo_preprocess_page(array &$variables): void {
  \Drupal::classResolver(PagePreprocess::class)($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function laszlo_preprocess_node(array &$variables): void {
  \Drupal::classResolver(NodePreprocess::class)($variables);
}
