block.settings.niklan_blog_post_tags:
  type: block_settings
  label: 'Blog post tags block'
  mapping:
    content:
      type: string
      label: Content

block.settings.niklan_search:
  type: block_settings
  label: 'Search block'
  mapping:
    content:
      type: string
      label: Content

filter_settings.niklan_markdown:
  type: filter
  label: 'Markdown filter'

field.formatter.settings.niklan_responsive_media_thumbnail:
  type: mapping
  label: 'Responsive media thumbnail formatter settings'
  mapping:
    image_link:
      type: string
      label: 'Link for image'
    responsive_image_style:
      type: string
      label: 'The responsive image style ID'
    image_loading:
      type: mapping
      label: 'Image loading settings'
      mapping:
        attribute:
          type: string
          label: 'Loading attribute'

field.formatter.settings.niklan_media_remote_video_optimized:
  type: mapping
  label: 'Optimized remote video formatter'
  mapping:
    responsive_image_style:
      type: string
      label: 'The responsive image style ID'
