name: CD

on:
  workflow_dispatch:

env:
  SSH_KEY: ${{ secrets.ci_deploy_key }}
  SSH_USER: ${{ secrets.ci_production_username }}
  SSH_HOST: ${{ secrets.ci_production_host }}
  # The root of an App. This where git root is.
  APP_ROOT: ${{ secrets.ci_app_root }}
  COMPOSER_BIN: docker compose exec -T php composer
  DRUSH_BIN: docker compose exec -T php drush

jobs:
  production:
    name: Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://niklan.net
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END

      - name: Pull changes
        shell: bash
        run: |
          ssh production "cd $APP_ROOT && git fetch && git checkout"
          ssh production "cd $APP_ROOT && git pull origin production"

      - name: Install Composer dependencies
        run: ssh production "cd $PROJECT_ROOT && $COMPOSER_BIN install --no-dev -o -n"

      - name: Deploy
        run: ssh production "cd $PROJECT_ROOT && $DRUSH_BIN deploy"

      - name: Clear PHP cache
        run: ssh production "cd $PROJECT_ROOT && docker compose exec -T php pkill -USR2 php-fpm"

      - name: Import custom translations
        run: ssh production "cd $PROJECT_ROOT && $COMPOSER_BIN locale-import"
