name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Composer
        if: always()
        run: task validate/composer

      - name: PHP lint
        if: always()
        run: task validate/phplint

      - name: PHPCS
        if: always()
        run: task validate/phpcs

      - name: PHPStan
        if: always()
        run: task validate/phpstan

      - name: JavaScript
        if: always()
        run: task validate/js

      - name: CSS
        if: always()
        run: task validate/css

      - name: YML
        if: always()
        run: task validate/yml

      - name: Spellcheck
        if: always()
        run: task validate/spellcheck

  phpunit:
    name: PHPUnit
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-website

      - name: Unit
        run: docker compose exec -T php task test/unit

      - name: Kernel
        run: docker compose exec -T php task test/kernel

      - name: Browser
        run: docker compose exec -T php task test/browser

      - name: Existing Site
        run: docker compose exec -T php task test/existing-site

      - name: Existing Site JavaScript
        run: docker compose exec -T php task test/existing-site-js
