name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  validate-composer:
    name: Validate Composer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Validate
        run: task validate/composer

  validate-phplint:
    name: Validate PHP lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Validate
        run: task validate/phplint

  validate-phpcs:
    name: Validate PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Validate
        run: task validate/phpcs

  validate-phpstan:
    name: Validate PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Validate
        run: task validate/phpstan

  validate-js:
    name: Validate JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Validate
        run: task validate/js

  validate-css:
    name: Validate CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Validate
        run: task validate/css

  validate-yml:
    name: Validate YML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Validate
        run: task validate/yml

  validate-spellcheck:
    name: Validate Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-validation

      - name: Validate
        run: task validate/spellcheck

  phpunit:
    name: PHPUnit
    needs:
      - validate-composer
      - validate-phplint
      - validate-phpcs
      - validate-phpstan
      - validate-js
      - validate-css
      - validate-yml
      - validate-spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/setup-website

      - name: Unit
        run: docker compose exec -T php task test/unit

      - name: Kernel
        run: docker compose exec -T php task test/kernel

      - name: Browser
        run: docker compose exec -T php task test/browser

      - name: Existing Site
        run: docker compose exec -T php task test/existing-site

      - name: Existing Site JavaScript
        run: docker compose exec -T php task test/existing-site-js
